/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Michael
 */
public class AdminMesas extends javax.swing.JFrame {

    /**
     * Creates new form AdminMesas
     */
    public AdminMesas() {
        initComponents();
    }
    
    private void estadoMesa(String mesa, String estado){
        if(estado.equals("1")){
            JOptionPane.showMessageDialog(rootPane, "Mesa "+ mesa+" ocupada con exito.");
        }
        if(estado.equals("2")){
            JOptionPane.showMessageDialog(rootPane, "Mesa "+ mesa+" desocupada con exito.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgMesa1 = new javax.swing.ButtonGroup();
        bgMesa2 = new javax.swing.ButtonGroup();
        bgMesa3 = new javax.swing.ButtonGroup();
        bgMesa4 = new javax.swing.ButtonGroup();
        bgMesa5 = new javax.swing.ButtonGroup();
        bgMesa6 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jrbOcuparMesa1 = new javax.swing.JRadioButton();
        jrbDesocuparMesa1 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jrbOcuparMesa2 = new javax.swing.JRadioButton();
        jrbDesocuparMesa2 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jrbOcuparMesa3 = new javax.swing.JRadioButton();
        jrbDesocuparMesa3 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jrbOcuparMesa4 = new javax.swing.JRadioButton();
        jrbDesocuparMesa4 = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jrbOcuparMesa5 = new javax.swing.JRadioButton();
        jrbDesocuparMesa5 = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jrbOcuparMesa6 = new javax.swing.JRadioButton();
        jrbDesocuparMesa6 = new javax.swing.JRadioButton();
        jbtnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Administrador de Mesas");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Mesa 1"));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mesa.jpg"))); // NOI18N

        bgMesa1.add(jrbOcuparMesa1);
        jrbOcuparMesa1.setText("Ocupar");
        jrbOcuparMesa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbOcuparMesa1ActionPerformed(evt);
            }
        });

        bgMesa1.add(jrbDesocuparMesa1);
        jrbDesocuparMesa1.setSelected(true);
        jrbDesocuparMesa1.setText("Desocupar");
        jrbDesocuparMesa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbDesocuparMesa1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbDesocuparMesa1)
                    .addComponent(jrbOcuparMesa1)
                    .addComponent(jLabel2))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jrbOcuparMesa1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbDesocuparMesa1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Mesa 2"));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mesa.jpg"))); // NOI18N

        bgMesa2.add(jrbOcuparMesa2);
        jrbOcuparMesa2.setText("Ocupar");
        jrbOcuparMesa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbOcuparMesa2ActionPerformed(evt);
            }
        });

        bgMesa2.add(jrbDesocuparMesa2);
        jrbDesocuparMesa2.setSelected(true);
        jrbDesocuparMesa2.setText("Desocupar");
        jrbDesocuparMesa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbDesocuparMesa2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbOcuparMesa2)
                    .addComponent(jLabel3)
                    .addComponent(jrbDesocuparMesa2))
                .addGap(45, 45, 45))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbOcuparMesa2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbDesocuparMesa2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Mesa 3"));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mesa.jpg"))); // NOI18N

        bgMesa3.add(jrbOcuparMesa3);
        jrbOcuparMesa3.setText("Ocupar");
        jrbOcuparMesa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbOcuparMesa3ActionPerformed(evt);
            }
        });

        bgMesa3.add(jrbDesocuparMesa3);
        jrbDesocuparMesa3.setSelected(true);
        jrbDesocuparMesa3.setText("Desocupar");
        jrbDesocuparMesa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbDesocuparMesa3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbDesocuparMesa3)
                    .addComponent(jrbOcuparMesa3)
                    .addComponent(jLabel4))
                .addGap(54, 54, 54))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbOcuparMesa3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbDesocuparMesa3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Mesa 4"));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mesa.jpg"))); // NOI18N

        bgMesa4.add(jrbOcuparMesa4);
        jrbOcuparMesa4.setText("Ocupar");
        jrbOcuparMesa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbOcuparMesa4ActionPerformed(evt);
            }
        });

        bgMesa4.add(jrbDesocuparMesa4);
        jrbDesocuparMesa4.setSelected(true);
        jrbDesocuparMesa4.setText("Desocupar");
        jrbDesocuparMesa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbDesocuparMesa4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbDesocuparMesa4)
                    .addComponent(jrbOcuparMesa4)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jrbOcuparMesa4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbDesocuparMesa4)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Mesa 5"));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mesa.jpg"))); // NOI18N

        bgMesa5.add(jrbOcuparMesa5);
        jrbOcuparMesa5.setText("Ocupar");
        jrbOcuparMesa5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbOcuparMesa5ActionPerformed(evt);
            }
        });

        bgMesa5.add(jrbDesocuparMesa5);
        jrbDesocuparMesa5.setSelected(true);
        jrbDesocuparMesa5.setText("Desocupar");
        jrbDesocuparMesa5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbDesocuparMesa5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jrbOcuparMesa5)
                    .addComponent(jrbDesocuparMesa5))
                .addGap(41, 41, 41))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbOcuparMesa5)
                .addGap(18, 18, 18)
                .addComponent(jrbDesocuparMesa5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Mesa 6"));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mesa.jpg"))); // NOI18N

        bgMesa6.add(jrbOcuparMesa6);
        jrbOcuparMesa6.setText("Ocupar");
        jrbOcuparMesa6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbOcuparMesa6ActionPerformed(evt);
            }
        });

        bgMesa6.add(jrbDesocuparMesa6);
        jrbDesocuparMesa6.setSelected(true);
        jrbDesocuparMesa6.setText("Desocupar");
        jrbDesocuparMesa6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbDesocuparMesa6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jrbOcuparMesa6)
                    .addComponent(jrbDesocuparMesa6))
                .addGap(49, 49, 49))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbOcuparMesa6)
                .addGap(18, 18, 18)
                .addComponent(jrbDesocuparMesa6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbtnSalir.setText("Salir");
        jbtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(jbtnSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(jLabel1)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jbtnSalir)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(800, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jrbOcuparMesa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbOcuparMesa1ActionPerformed
        // TODO add your handling code here:
        estadoMesa("1", "1");      
    }//GEN-LAST:event_jrbOcuparMesa1ActionPerformed

    private void jrbDesocuparMesa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbDesocuparMesa1ActionPerformed
        // TODO add your handling code here:
        estadoMesa("1", "2");
    }//GEN-LAST:event_jrbDesocuparMesa1ActionPerformed

    private void jrbOcuparMesa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbOcuparMesa2ActionPerformed
        // TODO add your handling code here:
        estadoMesa("2", "1");  
    }//GEN-LAST:event_jrbOcuparMesa2ActionPerformed

    private void jrbDesocuparMesa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbDesocuparMesa2ActionPerformed
        // TODO add your handling code here:
        estadoMesa("2", "2");
    }//GEN-LAST:event_jrbDesocuparMesa2ActionPerformed

    private void jrbOcuparMesa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbOcuparMesa3ActionPerformed
        // TODO add your handling code here:
        estadoMesa("3", "1");
    }//GEN-LAST:event_jrbOcuparMesa3ActionPerformed

    private void jrbDesocuparMesa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbDesocuparMesa3ActionPerformed
        // TODO add your handling code here:
        estadoMesa("3", "2");
    }//GEN-LAST:event_jrbDesocuparMesa3ActionPerformed

    private void jrbOcuparMesa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbOcuparMesa4ActionPerformed
        // TODO add your handling code here:
        estadoMesa("4", "1");
    }//GEN-LAST:event_jrbOcuparMesa4ActionPerformed

    private void jrbDesocuparMesa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbDesocuparMesa4ActionPerformed
        // TODO add your handling code here:
        estadoMesa("4", "2");
    }//GEN-LAST:event_jrbDesocuparMesa4ActionPerformed

    private void jrbOcuparMesa5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbOcuparMesa5ActionPerformed
        // TODO add your handling code here:
        estadoMesa("5", "1");
    }//GEN-LAST:event_jrbOcuparMesa5ActionPerformed

    private void jrbDesocuparMesa5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbDesocuparMesa5ActionPerformed
        // TODO add your handling code here:
        estadoMesa("5", "2");
    }//GEN-LAST:event_jrbDesocuparMesa5ActionPerformed

    private void jrbOcuparMesa6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbOcuparMesa6ActionPerformed
        // TODO add your handling code here:
        estadoMesa("6", "1");
    }//GEN-LAST:event_jrbOcuparMesa6ActionPerformed

    private void jrbDesocuparMesa6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbDesocuparMesa6ActionPerformed
        // TODO add your handling code here:
        estadoMesa("6", "2");
    }//GEN-LAST:event_jrbDesocuparMesa6ActionPerformed

    private void jbtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalirActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Hasta pronto");
        System.exit(0);
    }//GEN-LAST:event_jbtnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMesas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgMesa1;
    private javax.swing.ButtonGroup bgMesa2;
    private javax.swing.ButtonGroup bgMesa3;
    private javax.swing.ButtonGroup bgMesa4;
    private javax.swing.ButtonGroup bgMesa5;
    private javax.swing.ButtonGroup bgMesa6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton jbtnSalir;
    private javax.swing.JRadioButton jrbDesocuparMesa1;
    private javax.swing.JRadioButton jrbDesocuparMesa2;
    private javax.swing.JRadioButton jrbDesocuparMesa3;
    private javax.swing.JRadioButton jrbDesocuparMesa4;
    private javax.swing.JRadioButton jrbDesocuparMesa5;
    private javax.swing.JRadioButton jrbDesocuparMesa6;
    private javax.swing.JRadioButton jrbOcuparMesa1;
    private javax.swing.JRadioButton jrbOcuparMesa2;
    private javax.swing.JRadioButton jrbOcuparMesa3;
    private javax.swing.JRadioButton jrbOcuparMesa4;
    private javax.swing.JRadioButton jrbOcuparMesa5;
    private javax.swing.JRadioButton jrbOcuparMesa6;
    // End of variables declaration//GEN-END:variables
}
